opensearch-project/dashboards-investigation

- .github/CODEOWNERS
- MAINTAINERS.md
Add code owners and maintainers.
> feat: add code owners / maintainers

- common/types/notebooks.ts
- package.json
- public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
- public/components/notebooks/components/__tests__/notebook.test.tsx
- public/components/notebooks/components/input_panel.tsx
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/paragraph_components/input_panel.tsx
- public/components/notebooks/context_provider/context_provider.tsx
- public/components/notebooks/reducers/paragraphReducer.ts
- yarn.lock
add action input panel
https://github.com/user-attachments/assets/d3d64f1c-bb9c-4e99-b36e-2fe7902052c3
> Feature: add action input panel

- .github/CODEOWNERS
- .whitesource
> Add mend config

- public/components/notebooks/components/bubbleup/bubble_up_container.tsx
- public/components/notebooks/components/bubbleup/bubble_up_data_service.ts
- public/components/notebooks/components/notebook.tsx
> feat: add Anomaly Visualization Analysis atuomatically

- .github/workflows/dashboards-investigation-test-and-build-workflow.yml
- public/components/notebooks/components/notebook.tsx
- public/hooks/use_notebook.tsx
- public/hooks/use_paragraphs.tsx
> feat: minor fix for bubbleup and bring codecov back

- common/utils/paragraph.ts
- public/components/custom_panels/panel_modules/deep_research_container/deep_research_container.tsx
- public/components/notebooks/components/notebook.tsx
- public/utils/task.ts
- server/adaptors/notebooks/saved_objects_paragraphs_router.tsx
1. Move task updater inside deep research container
2. Store taskId and memoryId in output as object
3. Fix task state refresh issue
> Fix task state refresh issue

- opensearch_dashboards.json
- package.json
> feat: version bump to 3.2.0.0

- common/types/notebooks.ts
- public/components/notebooks/components/paragraph_components/log_pattern_container.tsx
- public/hooks/use_notebook.tsx
- public/hooks/use_precheck.tsx
integrate index insight in load notebook hook
https://github.com/user-attachments/assets/3879f1f7-13d4-49cf-a05e-4a2429818454
> feat: integrate index insight

- common/state/notebook_state.ts
- common/state/paragraph_state.ts
- common/types/notebooks.ts
- public/components/custom_panels/panel_modules/deep_research_container/deep_research_container.tsx
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/paragraph_components/paragraphs.tsx
- public/hooks/use_notebook.tsx
- public/hooks/use_paragraphs.tsx
- server/adaptors/notebooks/saved_objects_paragraphs_router.tsx
> feat: extract runParagraph as standalone hook

- public/components/custom_panels/panel_modules/deep_research_container/deep_research_container.tsx
- public/components/custom_panels/panel_modules/deep_research_container/message_trace_modal.tsx
- public/utils/__tests__/time.test.ts
- public/utils/time.ts
> Add step duration

- common/types/notebooks.ts
- public/hooks/use_notebook.tsx
> feat: update index insight

- server/paragraphs/ppl.ts
> Stringify ppl result when constructing prompt

- common/state/paragraph_state.ts
- public/components/notebooks/components/log_analytics/log_pattern_container.tsx
- public/components/notebooks/components/paragraph_components/deep_research/deep_research_output.tsx
- public/components/notebooks/components/paragraph_components/deep_research/message_trace_modal.tsx
- public/hooks/use_precheck.tsx
Make pre-check process more robust and simple. Please bear with the LLM json error in the end, that is not related to the change.
https://github.com/user-attachments/assets/2bd4d851-29ef-47b5-810d-9e8aea2e65b0
> feature: integrate PER agent with pre-checks

- common/constants/notebooks.ts
- server/common/helpers/notebooks/per_agent.ts
> feat: update prompt to comply with latest prompt change

- server/adaptors/notebooks/saved_objects_notebooks_router.tsx
- server/plugin.ts
- server/routes/index.ts
- server/routes/notebooks/notebook_router.ts
add owner for notebook and limit visibility for owner
> feat: add owner for notebook and limit visibility for owner

- common/types/notebooks.ts
- public/components/notebooks/components/bubbleup/bubble_up_container.tsx
- public/components/notebooks/components/bubbleup/bubble_up_data_service.ts
> fix: anomaly analysis loop fetch

- server/routes/utils.ts
Using UTC timezone to format time range.
> Format time range

- public/components/notebooks/components/log_analytics/components/pattern_difference.tsx
- public/components/notebooks/components/log_analytics/components/sequence_item.tsx
- server/routes/notebooks/log_pattern_router.ts
- server/services/ml_service.ts
1. replace agent api call to directly tool api call which don't need to provision a agent
2. sorting logic change for pattern difference, show unseen pattern on the top
> Replace agent call with  tool api call for log analysis

- public/components/notebooks/components/paragraph_components/deep_research/message_trace_modal.tsx
Use reason as sub step title like screenshot below
> Use reason as sub step title

- public/components/notebooks/components/input/input_context.tsx
- public/components/notebooks/components/input/input_type_selector.tsx
- public/components/notebooks/components/input/multi_variant_input.tsx
- public/components/notebooks/components/input/query_panel/language_toggle/index.ts
- public/components/notebooks/components/input/query_panel/language_toggle/language_toggle.scss
- public/components/notebooks/components/input/query_panel/language_toggle/language_toggle.tsx
- public/components/notebooks/components/input/query_panel/query_panel.tsx
- public/components/notebooks/components/input/query_panel/query_panel_editor.tsx
- public/components/notebooks/components/input/query_panel/use_query_panel_editor/use_query_panel_editor.ts
- public/components/notebooks/components/input/types.ts
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
https://github.com/user-attachments/assets/8e8d70ba-940f-487a-afbb-8395fe4f8e89
NA
> Support running SQL query in unified search bar

- common/state/paragraph_state.ts
- common/types/notebooks.ts
- public/components/notebooks/components/alert_panel.tsx
- public/components/notebooks/components/input/input_context.tsx
- public/components/notebooks/components/input/multi_variant_input.tsx
- public/components/notebooks/components/input/query_panel/query_panel.tsx
- public/components/notebooks/components/input/query_panel/query_panel_editor.tsx
- public/components/notebooks/components/input/types.ts
- public/components/notebooks/components/paragraph_components/deep_research/index.tsx
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
- public/hooks/use_paragraphs.ts
- public/hooks/use_precheck.tsx
- server/adaptors/notebooks/saved_objects_paragraphs_router.tsx
https://github.com/user-attachments/assets/81e3a689-a355-497a-9bce-05e8721ed9fd
- Automatically add PPL paragraph when it is triggered from discover page.
> feat: add PPL paragraph when jumping from discover

- common/types/notebooks.ts
- public/components/notebooks/components/__tests__/__snapshots__/notebook.test.tsx.snap
- public/components/notebooks/components/data_distribution/data_distribution_container.tsx
- public/components/notebooks/components/data_distribution/data_distribution_data_service.ts
- public/components/notebooks/components/data_distribution/data_distribution_viz.scss
- public/components/notebooks/components/data_distribution/render_data_distribution_vega.ts
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
- public/components/notebooks/index.scss
support show data distribution from discover
some style update:
- Prevent vega tooltip flashing
- Display the expand button after the mouse hovers over the para
https://github.com/user-attachments/assets/51b5ac38-e04a-49c9-9b09-789521a82c03
> feature: support show data distribution from discover

- public/components/notebooks/components/notebook_header.tsx
- public/hooks/use_notebook.tsx
1. Reset header variant when unmount
2. Catch index insight load error
> Reset header variant

- public/components/notebooks/components/data_distribution/data_distribution_container.tsx
- public/hooks/use_precheck.tsx
- public/utils/time.ts
Integrate discover trigger point
https://github.com/user-attachments/assets/ba957f18-3216-4df5-9012-52d2381c40dc
> Integrate discover trigger point

- public/components/notebooks/components/input/input_context.tsx
- public/components/notebooks/components/input/multi_variant_input.tsx
- public/components/notebooks/components/input/types.ts
- public/components/notebooks/components/input/use_agent_select_submit.ts
Change from `'DEEP_RESEARCH_AGENT'` to `'DEEP_RESEARCH'`
NA
> Fix deep research paragraph key

- common/state/notebook_state.ts
- common/state/paragraph_state.ts
- common/types/notebooks.ts
- public/components/notebooks/components/agents_selector.tsx
- public/components/notebooks/components/helpers/custom_modals/system_prompt_setting_modal.tsx
- public/components/notebooks/components/helpers/per_agent_helpers.ts
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/notebook_header.tsx
- public/components/notebooks/components/paragraph_components/deep_research/deep_research_output.tsx
- public/components/notebooks/components/paragraph_components/deep_research/index.tsx
- public/components/notebooks/components/paragraph_components/deep_research/message_trace_flyout.tsx
- public/components/notebooks/components/paragraph_components/deep_research/services/__tests__/per_agent_memory_service.test.ts
- public/components/notebooks/components/paragraph_components/deep_research/services/__tests__/per_agent_task_service.test.ts
- public/components/notebooks/components/paragraph_components/deep_research/services/per_agent_memory_service.ts
- public/components/notebooks/components/paragraph_components/deep_research/services/per_agent_task_service.ts
- public/components/notebooks/components/paragraph_components/deep_research/step_details_modal.tsx
- public/components/notebooks/components/paragraph_components/deep_research/utils.ts
- public/components/notebooks/components/paragraph_components/paragraph_actions_panel.tsx
- public/hooks/use_precheck.tsx
- public/utils/ml_commons_apis.ts
Refactor PER agent paragraph with chat style
> Refactor PER agent paragraph with chat style

- package.json
- public/components/notebooks/components/__tests__/notebook.test.tsx
- public/components/notebooks/components/paragraph_components/para_query_grid.tsx
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
- public/hooks/use_paragraphs.ts
- public/plugin.tsx
- public/services/context_service.test.ts
- public/services/context_service.ts
- public/services/index.ts
- public/types.ts
- yarn.lock
Store context data in IndexedDB, ensure ppl component will load context first when the component mounts.
for ppl context, we will store the query result as context
1. Set — Provide methods to update and save context for paragraph component
2. Get — Provide methods for paragraph component to retrieve context data by ID.
3. Delete — Provide a method to delete context
```
export interface ParagraphContext {
notebookId: string;
paragraphId: string;
// different paragraphs can have different context types, so temporarily use any here
context: any;
}
export interface ContextServiceSetup {
getParagraphContext: (
notebookId: string,
paragraphId: string
) => Promise<ParagraphContext | null>;
setParagraphContext: (paragraphContext: ParagraphContext) => Promise<boolean>;
deleteParagraphContext: …
```
> Add context service

- public/components/notebooks/components/input_panel.tsx
- public/components/notebooks/components/notebook.tsx
Scroll to the paragraph that new created from the InputPanel
> Scroll to the new created paragraph

- public/components/notebooks/components/__tests__/notebook.test.tsx
- public/components/notebooks/components/input/input_context.tsx
- public/components/notebooks/components/input/multi_variant_input.tsx
- public/components/notebooks/components/input/notebook_input/index.tsx
- public/components/notebooks/components/input/query_panel/get_prompt_mode_is_available/get_prompt_mode_is_available.test.ts
- public/components/notebooks/components/input/query_panel/get_prompt_mode_is_available/get_prompt_mode_is_available.ts
- public/components/notebooks/components/input/query_panel/index_selector.tsx/index_selector.scss
- public/components/notebooks/components/input/query_panel/index_selector.tsx/index_selector.tsx
- public/components/notebooks/components/input/query_panel/language_toggle/language_toggle.tsx
- public/components/notebooks/components/input/query_panel/query_panel.scss
- public/components/notebooks/components/input/query_panel/query_panel.tsx
- public/components/notebooks/components/input/query_panel/query_panel_editor.tsx
- public/components/notebooks/components/input/query_panel/use_query_panel_editor/use_query_panel_editor.ts
- public/components/notebooks/components/input/types.ts
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
- public/hooks/use_precheck.tsx
- public/utils/time.ts
https://github.com/user-attachments/assets/98bd7a16-f410-4a7a-9ce6-464cf9f16735
NA
> Add index select for query editor

- public/services/helpers/per_agent.ts
fix: unable to set ppl result to context
> fix: unable to set ppl result to context

- public/hooks/use_precheck.tsx
- public/services/helpers/per_agent.ts
- server/common/helpers/notebooks/per_agent.ts
> feat: minor changes

- public/utils/__tests__/query.test.ts
- public/utils/query.ts
Change to sort by _id
CPU usages being high
> Remove head 100 with random score sorting filter for PPL query

- .github/CODEOWNERS
- MAINTAINERS.md
Hailong has made significant contributions across multiple core features:
- Implemented log sequence/patterns paragraph ([PR #19](https://github.com/opensearch-project/dashboards-investigation/pull/19))
- Merged time range functionality ([PR #97](https://github.com/opensearch-project/dashboards-investigation/pull/97))
- Created the PPL parser service ([PR #76](https://github.com/opensearch-project/dashboards-investigation/pull/76))
- Developed index correlation & context updates ([PR #82](https://github.com/opensearch-project/dashboards-investigation/pull/82))
Additionally, Hailong has demonstrated project stewardship by actively reviewing PRs related to log analytics and PPL integration ([PR #73](https://github.com/opensearch-project/dashboards-investigation/pull/73), [PR …
> Add Hailong as maintainer

- opensearch_dashboards.json
- public/components/notebooks/components/__tests__/notebook.test.tsx
- public/components/notebooks/components/notebook.tsx
- public/hooks/use_context_subscription.tsx
- public/paragraphs/ppl.ts
- public/plugin.tsx
- public/types.ts
In order to make the whole flow works, you need to use
- OSD branch: https://github.com/ananzh/OpenSearch-Dashboards/tree/context-provider
- Assistant branch: https://github.com/SuZhou-Joe/dashboards-assistant/tree/feature/context_provider (This branch is used for illustrating how to use the context.)
Final result:
> Pass context to chatbot

- common/constants/ml_commons.ts
- common/state/notebook_state.ts
- common/types/notebooks.ts
- common/utils/per_agent.ts
- public/components/notebooks/components/hypotheses_panel.tsx
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/paragraph_components/markdown/index.tsx
- public/hooks/use_investigation.ts
- public/hooks/use_notebook.tsx
- public/hooks/use_paragraphs.ts
- public/utils/ml_commons_apis.ts
- server/adaptors/notebooks/saved_objects_paragraphs_router.tsx
- server/routes/notebooks/notebook_router.ts
- server/routes/notebooks/paragraph_router.ts
Add hypotheses panel like screenshot above.
> Run PER agent to generate hypotheses

- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/summary_card.tsx
> feat: issue summary card

- public/hooks/use_investigation.ts
Reduce replace hypothesis with similar findings
> Feat tuning investigation system prompt

- public/components/notebooks/components/input/query_panel/query_panel.tsx
- public/components/notebooks/components/input/visualization_input/index.tsx
- public/components/notebooks/components/input/visualization_input/use_visualization_input.ts
- public/components/notebooks/components/input_panel.tsx
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
- public/components/notebooks/components/paragraph_components/visualization/index.tsx
- public/components/notebooks/components/paragraph_components/visualization/use_visualization_value.ts
- server/common/helpers/notebooks/sample_notebooks.ts
> Fix visualization paragraph persist data structure

- public/components/notebooks/components/__tests__/note_table.test.tsx
- public/components/notebooks/components/__tests__/notebook.test.tsx
- public/components/notebooks/components/helpers/modal_containers.tsx
- public/components/notebooks/components/input/input_context.tsx
- public/components/notebooks/components/input/multi_variant_input.tsx
- public/components/notebooks/components/input_panel.tsx
- public/components/notebooks/components/note_table.tsx
- public/components/notebooks/components/notebook.tsx
- public/index.ts
- server/adaptors/notebooks/saved_objects_notebooks_router.tsx
- server/index.ts
- server/plugin.ts
- server/routes/index.ts
- server/routes/notebooks/notebook_router.ts
- server/routes/notebooks/paragraph_router.ts
Add agentic feature flag to hide some http routers and UI.
> feat: introduce agentic feature flag to gate agent related features

- public/components/notebooks/components/input/query_panel/query_panel.scss
> Fix date picker darkmode color

- common/utils/shared.ts
Notebook is able to run targeting a serverless, enable it.
> feat: support serverless opensearch engine type

- public/components/notebooks/components/input/notebook_input/index.scss
- public/components/notebooks/components/input/query_panel/index_selector.tsx/index_selector.tsx
- public/components/notebooks/components/input/query_panel/query_panel.tsx
- public/components/notebooks/components/notebook_header.tsx
- public/components/notebooks/components/paragraph_components/ppl/index.tsx
1. Fix input background color in dark mode
2. Fix issue of the sample notebook auto-cleared the query panel input
3. Fix header doesn't display for classic notebook
4. Fix sampling tooltip still displays for classic notebook which doesn't apply sampling
NA
> Various classic notebook minor fixes

- public/components/notebooks/components/input/query_panel/query_panel.scss
- public/components/notebooks/components/input/query_panel/query_panel.tsx
> Fix the execution of default query

- common/state/paragraph_state.ts
- public/components/notebooks/components/hypothesis/hypothesis_item.tsx
- public/components/notebooks/components/notebook.tsx
- public/components/notebooks/components/paragraph_components/markdown/index.tsx
- public/types.ts
- Auto open chatbot panel if chatbot is present.
- Auto shrink left nav.
- Make paragraph default mode to output only.
> Minor UX fix for hypothesis notebook
